server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/testdb
    username: jay3614
    password: 1234
  
  mvc:
    hiddenmethod:
      filter:
        enabled: false
        
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG
      
jwt:
  secret: AAAABBBBCCCCDDDDEEEEFFFFGGGG123!@#
